### ISSUE TITLE
Just a small improvement.

### ISSUE THREAD

**Issue by hendrixgr** [paparazzi/esp8266_udp_firmware#2]
Hi Christophe.
I didn't saw your esp8266 project until it was too late and i had already wrote a very simple program on my own when yours was excellent already...
Anyway because i use the Wemos D1 mini which has a built in ftdi chip it was needed to swap pins and make gpio13 the Rx and gpio15 the Tx. an action that it is needed if the board has already a ftdi chip which is connected to the default pins for UART0.
Here is what i added to your code.
In "wifi_config.h" i added #define ON_BOARD_USB_SERIAL_CHIP  1
and in the program i added this
void setup() {
  Serial.begin(SERIAL_BAUD_RATE);
//ADDED BY ME CODE
#if defined(ON_BOARD_USB_SERIAL_CHIP) && ON_BOARD_USB_SERIAL_CHIP == 1
#pragma message "UART PINS SWAPPED, GPIO 15 = TX and GPIO 13 = RX"
  pinMode(15, OUTPUT); // just to be sure...
  delay(200); // again just to be sure...
  Serial.swap(); // move UART0 pins, Rx to GPIO pin 13 and Tx to GPIO pin 15"
  delay(200);  // again just to be sure...
#endif
// END OF ADDED BY ME CODE  
rest of the code continues...

Chris.
.
.

**Comment by OpenUAS** [comment]
OK will add code to master as soon as I have ESP-01F documentation and build photos ready.

**Comment by OpenUAS** [comment]
Added to master code. a PR and merge will be performed asap
